### ISSUE TITLE
Set up CI/CD to bot's server

### ISSUE THREAD

**Issue by aleemet** [WaldurChatbot/Waldur-Chatbot#13]

**Comment by m2rtk** [comment]
Initial idea for CD is to create a bash script that will be deployed to remote server and executed using Travis. The script would pull this repository, install the dependencies using pip and start the components. Configuration info will be installed in remote server by hand before the deployment or added using Travis.

**Comment by m2rtk** [comment]
At the moment CD is setup in cd branch
