### ISSUE TITLE
Write tests

### ISSUE THREAD

**Issue by aleemet** [WaldurChatbot/Waldur-Chatbot#14]

**Comment by m2rtk** [comment]
Tests should be in the respective modules directory i.e. backend tests are in /backend/tests.py.
If multiple test scripts are created they should moved to a folder i.e. /backend/tests/test1.py and so on.

**Comment by m2rtk** [comment]
Done for common in aab6a921ac56052c704ceb6b8c64f5da8c3016a8
Done for backend in 6644defee17174eb8be3779d8a4a2d2e96d00707
