### ISSUE TITLE
Implement basic bot and responses.

### ISSUE THREAD

**Issue by aleemet** [WaldurChatbot/Waldur-Chatbot#15]
- [x] Implement basic bot
- [ ] Ask for repeated input if don't understand
- [ ] Respond to basic sentences like greetings.

**Comment by aleemet** [comment]
Issue migrated to https://github.com/WaldurChatbot/FleepBot/issues/1

**Comment by SilverKiro** [comment]
Associated [functional requirement](https://github.com/WaldurChatbot/Waldur-Chatbot/wiki/Functional-requirements): 1
