### ISSUE TITLE
Create more Requests for Waldur API

### ISSUE THREAD

**Issue by m2rtk** [WaldurChatbot/Waldur-Chatbot#22]
As of this moment we only have 2, which means we can only get 2 kinds of data from the Waldur API

**Comment by kyttike** [comment]
After next meeting with the client, we will expand this issue by creating child-issues and we will also track progress here.

**Comment by SilverKiro** [comment]
Associated [functional requirement](https://github.com/WaldurChatbot/Waldur-Chatbot/wiki/Functional-requirements): 3

**Comment by aleemet** [comment]
All child issues are listed here: https://github.com/WaldurChatbot/Waldur-Chatbot/issues?q=is%3Aissue+is%3Aopen+label%3Arequest

**Comment by aleemet** [comment]
Moved to 4th iteration as some requests should be implemented by then,

**Comment by SilverKiro** [comment]
Most of them are done.. just 1 (create VPC) is totally unimplemented, issues are in place, no need for this issue.
