### ISSUE TITLE
Improve text2rest

### ISSUE THREAD

**Issue by m2rtk** [WaldurChatbot/Waldur-Chatbot#23]
At the moment we just check if request contains certain words. Ex. if 'my' and 'projects' are in request string, we query user projects from Waldur API.

**Comment by kyttike** [comment]
Chatterbot's documentation will probably be helpful here.

Maybe identifying key-words is the way to go, as they would be processed by different adapters and trigger different api calls. 

Will there be a situation where same keywords can trigger different api calls depending on context?

**Comment by SilverKiro** [comment]
Associated [functional requirement](https://github.com/WaldurChatbot/Waldur-Chatbot/wiki/Functional-requirements): 1

**Comment by aleemet** [comment]
duplicate of #29
