### ISSUE TITLE
Implement a more secure authentication process

### ISSUE THREAD

**Issue by m2rtk** [WaldurChatbot/Waldur-Chatbot#24]
At the moment, we send our api keys directly from the chat. We should find a more secure solution.

**Comment by kyttike** [comment]
The client promised to also "assist" with this, in order to come up with a more pleasant authentication process, this will probably expanded to another issue.

**Comment by m2rtk** [comment]
Moved to 4th iteration, as for the moment, functionality > security

**Comment by SilverKiro** [comment]
Seems to be done.. Märt seems to have forgotten to link commits to it though
