### ISSUE TITLE
Write waldur specific training data for chatterbot

### ISSUE THREAD

**Issue by m2rtk** [WaldurChatbot/Waldur-Chatbot#25]
At the moment we are using chatterbots own [built-in training data](https://github.com/gunthercox/chatterbot-corpus) which isn't bad, but we should also implement something that is more related to Waldur itself.

**Comment by SilverKiro** [comment]
Associated [functional requirement](https://github.com/WaldurChatbot/Waldur-Chatbot/wiki/Functional-requirements): 1, 1.iv

**Comment by SilverKiro** [comment]
Associated [functional requirement](https://github.com/WaldurChatbot/Waldur-Chatbot/wiki/Functional-requirements): 1.iv

**Comment by aleemet** [comment]
Continued in #55
