### ISSUE TITLE
Implement a LogicAdapter capable of creating a VM

### ISSUE THREAD

**Issue by m2rtk** [WaldurChatbot/Waldur-Chatbot#27]
Create a VM, specifying IP type (public or private), the cloud, cloud type (public or private) and project it should be created to and the technical parameters like ram, cores and disk space.
Example input: 'Create a Centos7 VM with \<ip_type> IP in \<c_type> cloud \<c_name> in project \<p_name>. At least 5GB ram, 2 cores and 60GB disk'
[Request](https://github.com/WaldurChatbot/Waldur-Chatbot/wiki/Requests#create-a-virtual-machine)
[UC-19](https://github.com/WaldurChatbot/Waldur-Chatbot/wiki/Use-cases#uc-19)

**Comment by SilverKiro** [comment]
Associated [functional requirement](https://github.com/WaldurChatbot/Waldur-Chatbot/wiki/Functional-requirements): 3

**Comment by m2rtk** [comment]
Will be implemented using the InputRequest class

**Comment by aleemet** [comment]
Postponed to 4th Iteration as task proved to be much more time consuming as expected
