### ISSUE TITLE
Document all the possible requests the bot can do

### ISSUE THREAD

**Issue by m2rtk** [WaldurChatbot/Waldur-Chatbot#30]
Before we create any implementations, we should figure out which requests should be able to do.

**Comment by aleemet** [comment]
Currently, the following requests have been proposed:
* ~~Get VMs, their public IP's~~
* Get the total cost of an organisation, possibly as a graph (like it's presented in ETAIS) 
* ~~Get all organisations the user has access to~~
* Create a VM, specifying public ip, the cloud it should be created to and the technical parameters like ram, cores and disk space

**Comment by SilverKiro** [comment]
Associated [functional requirement](https://github.com/WaldurChatbot/Waldur-Chatbot/wiki/Functional-requirements): 3

**Comment by SilverKiro** [comment]
- Get team members in organisation/team
- Get audit log in project/organisation

**Comment by aleemet** [comment]
Client proposed requests: 
https://gist.github.com/livenson/411ec09912409eb79c1e4853c304f954

**Comment by SilverKiro** [comment]
Client has provided us with required requests. Will be documented in [requests](https://github.com/WaldurChatbot/Waldur-Chatbot/wiki/Requests) ASAP.

**Comment by SilverKiro** [comment]
All requests are now documented in [requests](https://github.com/WaldurChatbot/Waldur-Chatbot/wiki/Requests).
