### ISSUE TITLE
Implement request 'get_audit_log_organisation'

### ISSUE THREAD

**Issue by SilverKiro** [WaldurChatbot/Waldur-Chatbot#36]
What happened in organisation X.
Example input: "What happened in my organisation \<name>?" 
[Request](https://github.com/WaldurChatbot/Waldur-Chatbot/wiki/Requests#what-happened-in-organisation-x)
[UC-9](https://github.com/WaldurChatbot/Waldur-Chatbot/wiki/Use-cases#uc-9)

**Comment by SilverKiro** [comment]
Associated [functional requirement](https://github.com/WaldurChatbot/Waldur-Chatbot/wiki/Functional-requirements): 3

**Comment by SilverKiro** [comment]
Changed iteration to 4, no need to hurry with bad implementations and stuff :) better polish current requests first.

**Comment by aleemet** [comment]
The request should return last 10 log entries and for each entry should display its message, timestamp, user__fullname, event_type

**Comment by aleemet** [comment]
Implemented with b278537
