### ISSUE TITLE
Make the bot able to ask for confirmation and be capable of longer scripted conversations

### ISSUE THREAD

**Issue by m2rtk** [WaldurChatbot/Waldur-Chatbot#38]
Needed so we can create requests before which the bot asks for confirmation whether the user is sure they want to do it.

**Comment by SilverKiro** [comment]
Associated [functional requirement](https://github.com/WaldurChatbot/Waldur-Chatbot/wiki/Functional-requirements): 1.iii kind of.

**Comment by m2rtk** [comment]
Implemented in c905909fd7cd4ee1e8ed66ac861f82b6e0267fef
