### ISSUE TITLE
Implement request 'get_help'

### ISSUE THREAD

**Issue by SilverKiro** [WaldurChatbot/Waldur-Chatbot#42]
Explains what chatbot can do.
Example input: "Help." 
[Request](https://github.com/WaldurChatbot/Waldur-Chatbot/wiki/Requests#help)
[UC-14](https://github.com/WaldurChatbot/Waldur-Chatbot/wiki/Use-cases#uc-14)

**Comment by SilverKiro** [comment]
Associated [functional requirement](https://github.com/WaldurChatbot/Waldur-Chatbot/wiki/Functional-requirements): 3

**Comment by SilverKiro** [comment]
Associated [functional requirement](https://github.com/WaldurChatbot/Waldur-Chatbot/wiki/Functional-requirements): 1

**Comment by kyttike** [comment]
As we are not quite sure, if the solution, that we create, would be universal (or atleast good enough), we will postpone this to last iteration, once we have atleast 80% requests in place and we have a good picture of the whole deal
