### ISSUE TITLE
Implement request 'get_vms_project'

### ISSUE THREAD

**Issue by SilverKiro** [WaldurChatbot/Waldur-Chatbot#45]
List virtual machines in project X, organisation Y by type
Example input: "List all resources of type \<type> I have access to in project \<p_name>."
Example input: "List all resources of type \<type> I have access to in project \<p_name> organisation \<o_name>."
[Request](https://github.com/WaldurChatbot/Waldur-Chatbot/wiki/Requests#list-virtual-machines-in-project-x-organisation-y)
[UC-13](https://github.com/WaldurChatbot/Waldur-Chatbot/wiki/Use-cases#uc-13)

**Comment by SilverKiro** [comment]
Associated [functional requirement](https://github.com/WaldurChatbot/Waldur-Chatbot/wiki/Functional-requirements): 3

**Comment by aleemet** [comment]
implemented with 6608abc
