### ISSUE TITLE
Make 'get_services' request use parameter 'organisation'

### ISSUE THREAD

**Issue by SilverKiro** [WaldurChatbot/Waldur-Chatbot#52]
^
[Request](https://github.com/WaldurChatbot/Waldur-Chatbot/wiki/Requests#list-providers-in-organisation-x)

**Comment by SilverKiro** [comment]
Associated [functional requirement](https://github.com/WaldurChatbot/Waldur-Chatbot/wiki/Functional-requirements): 3

**Comment by aleemet** [comment]
Implemented with 3ccc5e3
