### ISSUE TITLE
Fix get_sevices implementation according to request

### ISSUE THREAD

**Issue by SilverKiro** [WaldurChatbot/Waldur-Chatbot#53]
[Request](https://github.com/WaldurChatbot/Waldur-Chatbot/wiki/Requests#list-providers-in-organisation-x)
[UC-4](https://github.com/WaldurChatbot/Waldur-Chatbot/wiki/Use-cases#uc-4)

**Comment by aleemet** [comment]
Implemented with 3ccc5e3
