### ISSUE TITLE
Whitespace is not ignored in users' input token... 

### ISSUE THREAD

**Issue by SilverKiro** [WaldurChatbot/Waldur-Chatbot#59]
Bot should ignore the whitespace in token, the token has to be stripped before querying from API.

**Comment by aleemet** [comment]
Fixed with 4ad10c7

**Comment by SilverKiro** [comment]
Should also ignore whitespace inside token, because api doesn't like it, maybeh?

**Comment by SilverKiro** [comment]
Oh it didn't actually  die anymore
