### ISSUE TITLE
Implement communication with Waldur REST api

### ISSUE THREAD

**Issue by aleemet** [WaldurChatbot/Waldur-Chatbot#6]

**Comment by m2rtk** [comment]
First implemented in 3e79fad177aa1ed73bd528eca4303c62a2691b12 
Improved in e56bfe36cf81dba19886e70370f4a9d3c173bd6f

**Comment by SilverKiro** [comment]
Associated [functional requirement](https://github.com/WaldurChatbot/Waldur-Chatbot/wiki/Functional-requirements): 3
