### ISSUE TITLE
Implement text2rest for querying data from Waldur API

### ISSUE THREAD

**Issue by aleemet** [WaldurChatbot/Waldur-Chatbot#7]

**Comment by m2rtk** [comment]
We need to redefine this issue, because as of 3e79fad177aa1ed73bd528eca4303c62a2691b12 we have a very basic text2rest implementation for one request, but I wouldn't say that this constitutes as solving this issue.

**Comment by m2rtk** [comment]
A simple implementation is done in 3e79fad177aa1ed73bd528eca4303c62a2691b12
Opened a new issue for improving this solution #23

**Comment by SilverKiro** [comment]
Associated [functional requirement](https://github.com/WaldurChatbot/Waldur-Chatbot/wiki/Functional-requirements): 1
