### ISSUE TITLE
Implement generating graphs from Waldur API data

### ISSUE THREAD

**Issue by aleemet** [WaldurChatbot/Waldur-Chatbot#9]

**Comment by m2rtk** [comment]
Changing milestone to 3rd as creating graphs from data does not seem to be in scope yet.

**Comment by m2rtk** [comment]
Changing milestone to 4th as this is not a very high priority feature.

**Comment by m2rtk** [comment]
Back to 3rd, as at the moment we are prioritizing functionality.

**Comment by SilverKiro** [comment]
Associated [functional requirement](https://github.com/WaldurChatbot/Waldur-Chatbot/wiki/Functional-requirements): 4

**Comment by SilverKiro** [comment]
Also provides implementation for request ['get_totalcosts'](https://github.com/WaldurChatbot/Waldur-Chatbot/wiki/Requests#show-expenses-of-organisation-with-a-chart) and [UC-7](https://github.com/WaldurChatbot/Waldur-Chatbot/wiki/Use-cases#uc-7).

**Comment by aleemet** [comment]
Postponed to 4th iteration
